---
  - name: "Create group"
    group: name={{ linux_group }} state=present
    tags:
        - always
        
  - name: "Create user and add to group"
    user: name={{ linux_user }} comment="{{ linux_user }} user" system=yes group={{ linux_group }}
    tags:
        - always
        
  - name: "Create user password"
    shell: usermod -p $(echo '{{ linux_password }}' | openssl passwd -1 -stdin) {{ linux_user }}
    tags:
        - always