---
# Install ruby from source when ruby_install_from_source is true.
- include: install-from-source.yml
  when: ruby_install_from_source == True

- name: Add user installed RubyGems bin directory to global $PATH.
  copy:
    src: rubygems.sh
    dest: /etc/profile.d/rubygems.sh
    mode: 0644

- name: Install ruby, rubygems, and build-essential
  apt: "name={{ item }} state=present"
  with_items:
    - ruby-full
    - ruby-dev
    - "{{ ruby_rubygems_package_name }}"
    - build-essential    
    
# Install Bundler and configured gems.
- name: Install Bundler
  gem: name=bundler state=present user_install=no
  when: ruby_install_bundler

- name: Install configured gems
  gem:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: "{{ ruby_install_gems_user }}"
  with_items: "{{ ruby_install_gems }}"

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Set rubygems package
  set_fact:
    ruby_rubygems_package_name: rubygems-integration
    
- name: Install gem rails
  command: sudo gem install rails    
  
- name: Install NodeJS and NPM
  apt: "name={{ item }} state=present"
  with_items:
    - npm
    - nodejs
 