---
# Setup application
- name: Creating Application test_app
  command: sudo rails new /var/www/test_app
  
- name: Change port to point over Nginx
  command: sudo sed -i 's/port        ENV.fetch("PORT") { 3000 }/port        ENV.fetch("PORT") { 80 }/' /var/www/test_app/config/puma.rb
  
- name: Creating Application test_app
  command: sudo /var/www/test_app/bin/rails server