---
 # System update
  - name: system update
    apt: 
       update_cache: yes
       cache_valid_time: 86400

# Install RVM
  - name: Append rvm path to environment
    lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{rvm_path}}).*?)(["]*)$' line="PATH=\1\2:{{rvm_path}}\3"
       
  - name: Ensure that GPG key for RVM is installed
    command: "gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3"
    args:
      creates: /root/.gnupg/secring.gpg

  - name: Ensure that RVM is installed
    shell: curl -L get.rvm.io | bash -s stable
    args:
      creates: /usr/local/rvm
